title: Supreeth Reddy Mamilla, PMP
logo: /assets/images/profile.jpg
description: >- # This means to ignore newlines until next key
  Advanced Business Analyst with over 10 years of experience in financial services, 
  retail industry, and healthcare sectors. Expert in Agile/Scrum delivery and end-to-end SDLC governance.
#show_downloads: true
theme: jekyll-theme-minimal
